server:
  port: 8080
spring:
  main:
    allow-circular-references: true
  application:
    # 应用的名称,可选,默认为项目名
    name: reggie
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 1234
  # 邮箱配置
  mail:
    host: smtp.qq.com  # 发送邮件的服务器地址
    username: 3088474946@qq.com # 开启 IMAP/SMTP服务 的qq邮箱的账号
    password: qmzuscrqlbysdehj # 开启 IMAP/SMTP服务 获得的授权码,而不是qq邮箱的登录密码
    default-encoding: UTF-8
  # redis配置
  redis:
    host: localhost
    port: 6379
    #    password: root
    database: 0  # 默认使用 0号db
    cache:
      redis:
        time-to-live: 1800000  # 设置缓存数据的过期时间，30分钟

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true

    #日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
# 自定义路径
reggie:
  path: C:\Users\Freeman\Desktop\picture2\
